version: "3.9"
services:
 configdb:
    image: ${CONFIGDB_IMAGE}:${CONFIGDB_VERSION}
    container_name: postgres
    restart: always
    user: postgres
    secrets:
      - configdb-password
    volumes:
      - ctrl_configdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/configdb-password
    expose:
      - 5432
    networks:
      - ctrl_internal
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

 redis:
    image: ${REDIS_IMAGE}:${REDIS_VERSION}
    container_name: redis
    restart: always
    volumes:
      - ctrl_redis_data:/var/lib/redis/data
    expose:
      - 6379
    networks:
      - ctrl_internal

 apisvc:
    image: ${APISERVICE_IMAGE}:${APISERVICE_VERSION}
    container_name: apiservice
    restart: always
    networks:
      - ctrl_internal
    depends_on:
      - configdb
      - redis
    links:
      - configdb
      - redis

volumes:
  ctrl_configdb_data:
    name: configdb_data
  ctrl_redis_data:
    name: redis_data

secrets:
  configdb-password:
    file: configdb/password

networks:
  ctrl_external:
    name: extnet
  ctrl_internal:
    name: intnet
