version: "3.9"
services:
 configdb:
    image: ${CONFIGDB_IMAGE}:${CONFIGDB_VERSION}
    container_name: postgres
    restart: always
    user: postgres
    secrets:
      - configdb-password
    volumes:
      - configdb-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/configdb-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
 redis:
    image: ${REDIS_IMAGE}:${REDIS_VERSION}
    container_name: redis
    restart: always
    volumes:
      - redis-data:/var/lib/redis/data
    expose:
      - 6379
 apisvc:
    image: ${APISERVICE_IMAGE}:${APISERVICE_VERSION}
    container_name: apiservice
    restart: always

volumes:
  configdb-data:
  redis-data:

secrets:
  configdb-password:
    file: configdb/password
