#!/bin/bash

if [[ $1 == "start" ]]; then
    make ctrl-build && make ctrl-start
elif [[ $1 == "stop" ]]; then
    make ctrl-stop-clean
elif [[ $1 == "stop-clean" ]]; then
    make ctrl-stop-clean
    make ctrl-build-clean
fi
