version: "3.9"
services:
  vault:
    image: ${VAULT_IMAGE}:${VAULT_VERSION}
    container_name: vault
    restart: always
    expose:
      - 8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
      - ./vault/tokens/root:/vault/tokens/root
      - ./vault/tokens/drio-controller:/vault/tokens/drio-controller
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_SECRET_SHARES=${VAULT_SECRET_SHARES}
      - VAULT_SECRET_THRESHOLD=${VAULT_SECRET_THRESHOLD}
    command: /start-vault.sh
    cap_add:
      - IPC_LOCK
    networks:
      - vaultnet

networks:
  vaultnet:
    name: vaultnet
