version: "3.9"
services:
  vault-agent-init:
    image: ${VAULT_AGENT_IMAGE}:${VAULT_AGENT_VERSION}
    container_name: vault-agent-init
    networks:
      - ctrl_internal
      - ctrl_vaultnet
      - vaultagentnet
    volumes:
      - ../../vault/compose/tokens/drio-controller:/etc/vault/tokens:ro
      - ./role_id:/etc/vault/role_id
      - ./secret_id:/etc/vault/secret_id
    entrypoint: /vault-agent-init.sh

  vault-agent:
    image: ${VAULT_AGENT_IMAGE}:${VAULT_AGENT_VERSION}
    container_name: vault-agent
    networks:
      - ctrl_internal
      - ctrl_vaultnet
      - vaultagentnet
    volumes:
      - ./role_id:/etc/vault/role_id:ro
      - ./secret_id:/etc/vault/secret_id:ro
    expose:
      - 8100
    depends_on:
      - vault-agent-init

networks:
  ctrl_internal:
    name: intnet
    external: true
  ctrl_vaultnet:
    name: vaultnet
    external: true
  vaultagentnet:
    name: vaultagentnet

