services:
  pubsub:
    image: ${PUBSUB_IMAGE}:${PUBSUB_VERSION}
    hostname: pubsub
    container_name: pubsub
    restart: always
    networks:
      - ctrl_internal
      - ctrl_vaultnet
    expose:
      - 9092
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://pubsub:9092,PLAINTEXT://pubsub:19092
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_SASL_ENABLED_MECHANISMS=SCRAM-SHA-256
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAINTEXT
      - KAFKA_SUPER_USERS=User:drio
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@pubsub:29093
      - KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
      - VAULT_ADDR=http://vault:8200
    env_file:
      - ../../vault/compose/tokens/drio-controller/drio-controller-role.env

networks:
  ctrl_internal:
    name: intnet
  ctrl_vaultnet:
    name: vaultnet
    external: true
