version: "3.9"
services:
  configdb:
    image: ${CONFIGDB_IMAGE}:${CONFIGDB_VERSION}
    container_name: postgres
    restart: always
    user: postgres
    secrets:
      - configdb-password
    volumes:
      - ctrl_configdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/configdb-password
      - VAULT_ADDR=http://vault:8200
    env_file:
      - ../../vault/compose/tokens/drio-controller/drio-controller-role.env
    expose:
      - 5432
    networks:
      - ctrl_internal
      - ctrl_vaultnet
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: ${REDIS_IMAGE}:${REDIS_VERSION}
    container_name: redis
    restart: always
    volumes:
      - ctrl_redis_data:/var/lib/redis/data
    expose:
      - 6379
    networks:
      - ctrl_internal

  redis-init:
    image: ${REDIS_IMAGE}:${REDIS_VERSION}
    container_name: redis-init
    restart: "no"
    volumes:
      - ctrl_redis_data:/var/lib/redis/data
    environment:
      - VAULT_ADDR=http://vault:8200
      - REDIS_HOST=redis
    env_file:
      - ../../vault/compose/tokens/drio-controller/drio-controller-role.env
    entrypoint: /init-redis.sh
    expose:
      - 6379
    depends_on:
      - redis
    links:
      - redis
    networks:
      - ctrl_internal
      - ctrl_vaultnet

  apisvc:
    image: ${APISERVICE_IMAGE}:${APISERVICE_VERSION}
    container_name: apiservice
    restart: always
    volumes:
      - ../../vault/compose/tokens/drio-controller/drio-controller-role.env:/etc/apiservice/drio-controller-role.env:ro
    networks:
      - ctrl_internal
      - ctrl_vaultnet
    depends_on:
      - configdb
      - redis
      - redis-init
    links:
      - configdb
      - redis

volumes:
  ctrl_configdb_data:
    name: configdb_data
  ctrl_redis_data:
    name: redis_data

secrets:
  configdb-password:
    file: configdb/password

networks:
  ctrl_external:
    name: extnet
  ctrl_internal:
    name: intnet
  ctrl_vaultnet:
    name: vaultnet
    external: true
