services:
  configdb:
    image: ${CONFIGDB_IMAGE}:${CONFIGDB_VERSION}
    container_name: postgres
    command:
      - -ctcp_keepalives_idle=20
      - -ctcp_keepalives_interval=3
      - -ctcp_keepalives_count=3
    restart: always
    user: postgres
    secrets:
      - configdb-password
    volumes:
      - ctrl_configdb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/configdb-password
      - VAULT_ADDR=http://vault:8200
      - DRIO_DEFAULT_SAAS_ADMINS=${DRIO_DEFAULT_SAAS_ADMINS}
      - DRIO_SAAS_ADMINS=${DRIO_SAAS_ADMINS:-""}
    env_file:
      - ../../vault/compose/tokens/drio-controller/drio-controller-role.env
    expose:
      - ${CONFIGDB_PORT}
    networks:
      - ctrl_internal
      - ctrl_vaultnet
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  vault-agent:
    image: ${VAULT_AGENT_IMAGE}:${VAULT_AGENT_VERSION}
    container_name: vault-agent
    networks:
      - ctrl_internal
      - ctrl_vaultnet
    volumes:
      - ../../vault/compose/tokens/drio-controller:/etc/vault/tokens:ro
      - ./vault-agent:/etc/vault/agent
    expose:
      - ${VAULT_AGENT_LISTEN_PORT}

  apiservice-init:
    image: ${APISERVICE_IMAGE}:${APISERVICE_VERSION}
    container_name: apiservice-init
    command:
      - --init-only
      - --deployment=${APISERVICE_DEPLOYMENT_TYPE}
    restart: "no"
    volumes:
      - ../../vault/compose/tokens/drio-controller/drio-controller-role.env:/etc/apiservice/drio-controller-role.env:ro
      - ./vault-agent:/etc/vault/agent:ro
    networks:
      - ctrl_internal
      - ctrl_vaultnet
    depends_on:
      vault-agent:
        condition: service_started
      configdb:
        condition: service_healthy
    links:
      - configdb

  apiservice:
    image: ${APISERVICE_IMAGE}:${APISERVICE_VERSION}
    scale: ${APISERVICE_SCALE}
    command:
      - --deployment=${APISERVICE_DEPLOYMENT_TYPE}
    restart: always
    volumes:
      - ../../vault/compose/tokens/drio-controller/drio-controller-role.env:/etc/apiservice/drio-controller-role.env:ro
      - ./vault-agent:/etc/vault/agent:ro
    networks:
      - ctrl_internal
      - ctrl_vaultnet
    ports:
      - ${APISERVICE_PORT}
    depends_on:
      configdb:
        condition: service_healthy
      apiservice-init:
        condition: service_completed_successfully
    links:
      - configdb
    healthcheck:
      test: [ "CMD", "/etc/apiservice/bin/status.sh", "${APISERVICE_DEPLOYMENT_TYPE}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: ${NGINX_IMAGE}:${NGINX_VERSION}
    container_name: loadbalancer
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ctrl_internal
    ports:
      - ${NGINX_LISTEN_PORT}:${NGINX_LISTEN_PORT}
    depends_on:
      apiservice:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ctrl_configdb_data:
    name: configdb_data

secrets:
  configdb-password:
    file: configdb/password

networks:
  ctrl_external:
    name: extnet
  ctrl_internal:
    name: intnet
    external: true
  ctrl_vaultnet:
    name: vaultnet
    external: true
