FROM redis:7.0.11 AS drioredis

LABEL maintainer="Sudarsan Raghavan <sraghavan@drio.ai>"
LABEL company="Drio Inc"
LABEL component="Drio Controller"

RUN apt update -y && apt upgrade curl jq -y
COPY docker/conf/redis.conf /usr/local/etc/redis/redis.conf
COPY docker/redisinit/init-redis.sh /
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf", "--save", "60", "1", "--loglevel", "warning" ]
