#!/bin/bash

if [[ $1 == "start" ]]; then
    make image && make start
    vault_status=$(docker ps --filter "name=vault" --filter "status=running" | grep -w vault)
    if [[ -z ${vault_status} ]]; then
        echo "Failed to start vault"
        exit 1
    fi

    sleep 10
    docker exec -ti vault /init-vault.sh
elif [[ $1 == "stop" ]]; then
    make stop-clean
elif [[ $1 == "stop-clean" ]]; then
    make stop-clean
    make clean
fi
