services:
  vault:
    image: ${VAULT_IMAGE}:${VAULT_VERSION}
    container_name: vault
    restart: always
    expose:
      - 8200
    volumes:
      - ./config:/vault/config
      - ./policies:/vault/policies
      - ./data:/vault/data
      - ./logs:/vault/logs
      - ./tokens/root:/vault/tokens/root
      - ./tokens/drio-controller:/vault/tokens/drio-controller
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_SECRET_SHARES=${VAULT_SECRET_SHARES}
      - VAULT_SECRET_THRESHOLD=${VAULT_SECRET_THRESHOLD}
    command: vault server -config=/vault/config/config.json
    cap_add:
      - IPC_LOCK
    networks:
      - vaultnet

  vault-init:
    image: ${VAULT_IMAGE}:${VAULT_VERSION}
    container_name: vault-init
    restart: "no"
    volumes:
      - ./config:/vault/config
      - ./policies:/vault/policies
      - ./data:/vault/data
      - ./logs:/vault/logs
      - ./tokens/root:/vault/tokens/root
      - ./tokens/drio-controller:/vault/tokens/drio-controller
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_API_ADDR=http://vault:8200
      - VAULT_SECRET_SHARES=${VAULT_SECRET_SHARES}
      - VAULT_SECRET_THRESHOLD=${VAULT_SECRET_THRESHOLD}
    entrypoint: /init-vault.sh
    depends_on:
      - vault
    links:
      - vault
    networks:
      - vaultnet

networks:
  vaultnet:
    name: vaultnet
