#!/bin/bash

if [ $1 == "build-start" ]; then
    make image
fi

if [ $1 == "build-start" -o $1 == "start" ]; then
    make start
fi

if [ $1 == "stop" -o $1 == "stop-clean" ]; then
    make stop-clean
fi

if [ $1 == "stop-clean" ]; then
    make clean
fi
